FROM golang:1.18.8-alpine3.16 as builder

COPY . /channeld

WORKDIR /channeld/{WorkDir}

ENV GOPROXY="https://goproxy.io"
RUN go get -d -v ./...
RUN go install -v ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o . ./...

FROM alpine as prod

COPY --from=builder /channeld/{WorkDir}/{AppName} .
COPY ./config ./config

EXPOSE 12108
EXPOSE 11288

ENTRYPOINT ["./{AppName}"]