// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unreal_common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_unreal_5fcommon_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_unreal_5fcommon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_unreal_5fcommon_2eproto CHANNELDUE_API
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct CHANNELDUE_API TableStruct_unreal_5fcommon_2eproto {
  static const uint32_t offsets[];
};
CHANNELDUE_API extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_unreal_5fcommon_2eproto;
namespace unrealpb {
class FVector;
struct FVectorDefaultTypeInternal;
CHANNELDUE_API extern FVectorDefaultTypeInternal _FVector_default_instance_;
class SceneComponentState;
struct SceneComponentStateDefaultTypeInternal;
CHANNELDUE_API extern SceneComponentStateDefaultTypeInternal _SceneComponentState_default_instance_;
class UnrealObjectRef;
struct UnrealObjectRefDefaultTypeInternal;
CHANNELDUE_API extern UnrealObjectRefDefaultTypeInternal _UnrealObjectRef_default_instance_;
}  // namespace unrealpb
PROTOBUF_NAMESPACE_OPEN
template<> CHANNELDUE_API ::unrealpb::FVector* Arena::CreateMaybeMessage<::unrealpb::FVector>(Arena*);
template<> CHANNELDUE_API ::unrealpb::SceneComponentState* Arena::CreateMaybeMessage<::unrealpb::SceneComponentState>(Arena*);
template<> CHANNELDUE_API ::unrealpb::UnrealObjectRef* Arena::CreateMaybeMessage<::unrealpb::UnrealObjectRef>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace unrealpb {

// ===================================================================

class CHANNELDUE_API FVector final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:unrealpb.FVector) */ {
 public:
  inline FVector() : FVector(nullptr) {}
  ~FVector() override;
  explicit PROTOBUF_CONSTEXPR FVector(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FVector(const FVector& from);
  FVector(FVector&& from) noexcept
    : FVector() {
    *this = ::std::move(from);
  }

  inline FVector& operator=(const FVector& from) {
    CopyFrom(from);
    return *this;
  }
  inline FVector& operator=(FVector&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FVector& default_instance() {
    return *internal_default_instance();
  }
  static inline const FVector* internal_default_instance() {
    return reinterpret_cast<const FVector*>(
               &_FVector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FVector& a, FVector& b) {
    a.Swap(&b);
  }
  inline void Swap(FVector* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FVector* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FVector* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FVector>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FVector& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FVector& from) {
    FVector::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FVector* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "unrealpb.FVector";
  }
  protected:
  explicit FVector(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:unrealpb.FVector)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unreal_5fcommon_2eproto;
};
// -------------------------------------------------------------------

class CHANNELDUE_API UnrealObjectRef final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:unrealpb.UnrealObjectRef) */ {
 public:
  inline UnrealObjectRef() : UnrealObjectRef(nullptr) {}
  ~UnrealObjectRef() override;
  explicit PROTOBUF_CONSTEXPR UnrealObjectRef(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnrealObjectRef(const UnrealObjectRef& from);
  UnrealObjectRef(UnrealObjectRef&& from) noexcept
    : UnrealObjectRef() {
    *this = ::std::move(from);
  }

  inline UnrealObjectRef& operator=(const UnrealObjectRef& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnrealObjectRef& operator=(UnrealObjectRef&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnrealObjectRef& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnrealObjectRef* internal_default_instance() {
    return reinterpret_cast<const UnrealObjectRef*>(
               &_UnrealObjectRef_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UnrealObjectRef& a, UnrealObjectRef& b) {
    a.Swap(&b);
  }
  inline void Swap(UnrealObjectRef* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnrealObjectRef* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnrealObjectRef* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnrealObjectRef>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnrealObjectRef& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnrealObjectRef& from) {
    UnrealObjectRef::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnrealObjectRef* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "unrealpb.UnrealObjectRef";
  }
  protected:
  explicit UnrealObjectRef(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetGUIDFieldNumber = 1,
  };
  // uint32 NetGUID = 1;
  void clear_netguid();
  uint32_t netguid() const;
  void set_netguid(uint32_t value);
  private:
  uint32_t _internal_netguid() const;
  void _internal_set_netguid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:unrealpb.UnrealObjectRef)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t netguid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unreal_5fcommon_2eproto;
};
// -------------------------------------------------------------------

class CHANNELDUE_API SceneComponentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:unrealpb.SceneComponentState) */ {
 public:
  inline SceneComponentState() : SceneComponentState(nullptr) {}
  ~SceneComponentState() override;
  explicit PROTOBUF_CONSTEXPR SceneComponentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SceneComponentState(const SceneComponentState& from);
  SceneComponentState(SceneComponentState&& from) noexcept
    : SceneComponentState() {
    *this = ::std::move(from);
  }

  inline SceneComponentState& operator=(const SceneComponentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneComponentState& operator=(SceneComponentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneComponentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneComponentState* internal_default_instance() {
    return reinterpret_cast<const SceneComponentState*>(
               &_SceneComponentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SceneComponentState& a, SceneComponentState& b) {
    a.Swap(&b);
  }
  inline void Swap(SceneComponentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneComponentState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneComponentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SceneComponentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SceneComponentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SceneComponentState& from) {
    SceneComponentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SceneComponentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "unrealpb.SceneComponentState";
  }
  protected:
  explicit SceneComponentState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttachChildrenFieldNumber = 10,
    kAttachSocketNameFieldNumber = 11,
    kAttachParentFieldNumber = 9,
    kRelativeLocationFieldNumber = 12,
    kRelativeRotationFieldNumber = 13,
    kRelativeScaleFieldNumber = 14,
    kRemovedFieldNumber = 1,
    kBAbsoluteLocationFieldNumber = 2,
    kBAbsoluteRotationFieldNumber = 3,
    kBAbsoluteScaleFieldNumber = 4,
    kBVisibleFieldNumber = 5,
    kBShouldBeAttachedFieldNumber = 6,
    kBShouldSnapLocationWhenAttachedFieldNumber = 7,
    kBShouldSnapRotationWhenAttachedFieldNumber = 8,
  };
  // repeated .unrealpb.UnrealObjectRef attachChildren = 10;
  int attachchildren_size() const;
  private:
  int _internal_attachchildren_size() const;
  public:
  void clear_attachchildren();
  ::unrealpb::UnrealObjectRef* mutable_attachchildren(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::unrealpb::UnrealObjectRef >*
      mutable_attachchildren();
  private:
  const ::unrealpb::UnrealObjectRef& _internal_attachchildren(int index) const;
  ::unrealpb::UnrealObjectRef* _internal_add_attachchildren();
  public:
  const ::unrealpb::UnrealObjectRef& attachchildren(int index) const;
  ::unrealpb::UnrealObjectRef* add_attachchildren();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::unrealpb::UnrealObjectRef >&
      attachchildren() const;

  // string attachSocketName = 11;
  void clear_attachsocketname();
  const std::string& attachsocketname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_attachsocketname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_attachsocketname();
  PROTOBUF_NODISCARD std::string* release_attachsocketname();
  void set_allocated_attachsocketname(std::string* attachsocketname);
  private:
  const std::string& _internal_attachsocketname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_attachsocketname(const std::string& value);
  std::string* _internal_mutable_attachsocketname();
  public:

  // .unrealpb.UnrealObjectRef attachParent = 9;
  bool has_attachparent() const;
  private:
  bool _internal_has_attachparent() const;
  public:
  void clear_attachparent();
  const ::unrealpb::UnrealObjectRef& attachparent() const;
  PROTOBUF_NODISCARD ::unrealpb::UnrealObjectRef* release_attachparent();
  ::unrealpb::UnrealObjectRef* mutable_attachparent();
  void set_allocated_attachparent(::unrealpb::UnrealObjectRef* attachparent);
  private:
  const ::unrealpb::UnrealObjectRef& _internal_attachparent() const;
  ::unrealpb::UnrealObjectRef* _internal_mutable_attachparent();
  public:
  void unsafe_arena_set_allocated_attachparent(
      ::unrealpb::UnrealObjectRef* attachparent);
  ::unrealpb::UnrealObjectRef* unsafe_arena_release_attachparent();

  // .unrealpb.FVector relativeLocation = 12;
  bool has_relativelocation() const;
  private:
  bool _internal_has_relativelocation() const;
  public:
  void clear_relativelocation();
  const ::unrealpb::FVector& relativelocation() const;
  PROTOBUF_NODISCARD ::unrealpb::FVector* release_relativelocation();
  ::unrealpb::FVector* mutable_relativelocation();
  void set_allocated_relativelocation(::unrealpb::FVector* relativelocation);
  private:
  const ::unrealpb::FVector& _internal_relativelocation() const;
  ::unrealpb::FVector* _internal_mutable_relativelocation();
  public:
  void unsafe_arena_set_allocated_relativelocation(
      ::unrealpb::FVector* relativelocation);
  ::unrealpb::FVector* unsafe_arena_release_relativelocation();

  // .unrealpb.FVector relativeRotation = 13;
  bool has_relativerotation() const;
  private:
  bool _internal_has_relativerotation() const;
  public:
  void clear_relativerotation();
  const ::unrealpb::FVector& relativerotation() const;
  PROTOBUF_NODISCARD ::unrealpb::FVector* release_relativerotation();
  ::unrealpb::FVector* mutable_relativerotation();
  void set_allocated_relativerotation(::unrealpb::FVector* relativerotation);
  private:
  const ::unrealpb::FVector& _internal_relativerotation() const;
  ::unrealpb::FVector* _internal_mutable_relativerotation();
  public:
  void unsafe_arena_set_allocated_relativerotation(
      ::unrealpb::FVector* relativerotation);
  ::unrealpb::FVector* unsafe_arena_release_relativerotation();

  // .unrealpb.FVector relativeScale = 14;
  bool has_relativescale() const;
  private:
  bool _internal_has_relativescale() const;
  public:
  void clear_relativescale();
  const ::unrealpb::FVector& relativescale() const;
  PROTOBUF_NODISCARD ::unrealpb::FVector* release_relativescale();
  ::unrealpb::FVector* mutable_relativescale();
  void set_allocated_relativescale(::unrealpb::FVector* relativescale);
  private:
  const ::unrealpb::FVector& _internal_relativescale() const;
  ::unrealpb::FVector* _internal_mutable_relativescale();
  public:
  void unsafe_arena_set_allocated_relativescale(
      ::unrealpb::FVector* relativescale);
  ::unrealpb::FVector* unsafe_arena_release_relativescale();

  // bool removed = 1;
  void clear_removed();
  bool removed() const;
  void set_removed(bool value);
  private:
  bool _internal_removed() const;
  void _internal_set_removed(bool value);
  public:

  // bool bAbsoluteLocation = 2;
  void clear_babsolutelocation();
  bool babsolutelocation() const;
  void set_babsolutelocation(bool value);
  private:
  bool _internal_babsolutelocation() const;
  void _internal_set_babsolutelocation(bool value);
  public:

  // bool bAbsoluteRotation = 3;
  void clear_babsoluterotation();
  bool babsoluterotation() const;
  void set_babsoluterotation(bool value);
  private:
  bool _internal_babsoluterotation() const;
  void _internal_set_babsoluterotation(bool value);
  public:

  // bool bAbsoluteScale = 4;
  void clear_babsolutescale();
  bool babsolutescale() const;
  void set_babsolutescale(bool value);
  private:
  bool _internal_babsolutescale() const;
  void _internal_set_babsolutescale(bool value);
  public:

  // bool bVisible = 5;
  void clear_bvisible();
  bool bvisible() const;
  void set_bvisible(bool value);
  private:
  bool _internal_bvisible() const;
  void _internal_set_bvisible(bool value);
  public:

  // bool bShouldBeAttached = 6;
  void clear_bshouldbeattached();
  bool bshouldbeattached() const;
  void set_bshouldbeattached(bool value);
  private:
  bool _internal_bshouldbeattached() const;
  void _internal_set_bshouldbeattached(bool value);
  public:

  // bool bShouldSnapLocationWhenAttached = 7;
  void clear_bshouldsnaplocationwhenattached();
  bool bshouldsnaplocationwhenattached() const;
  void set_bshouldsnaplocationwhenattached(bool value);
  private:
  bool _internal_bshouldsnaplocationwhenattached() const;
  void _internal_set_bshouldsnaplocationwhenattached(bool value);
  public:

  // bool bShouldSnapRotationWhenAttached = 8;
  void clear_bshouldsnaprotationwhenattached();
  bool bshouldsnaprotationwhenattached() const;
  void set_bshouldsnaprotationwhenattached(bool value);
  private:
  bool _internal_bshouldsnaprotationwhenattached() const;
  void _internal_set_bshouldsnaprotationwhenattached(bool value);
  public:

  // @@protoc_insertion_point(class_scope:unrealpb.SceneComponentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::unrealpb::UnrealObjectRef > attachchildren_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr attachsocketname_;
    ::unrealpb::UnrealObjectRef* attachparent_;
    ::unrealpb::FVector* relativelocation_;
    ::unrealpb::FVector* relativerotation_;
    ::unrealpb::FVector* relativescale_;
    bool removed_;
    bool babsolutelocation_;
    bool babsoluterotation_;
    bool babsolutescale_;
    bool bvisible_;
    bool bshouldbeattached_;
    bool bshouldsnaplocationwhenattached_;
    bool bshouldsnaprotationwhenattached_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unreal_5fcommon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FVector

// float x = 1;
inline void FVector::clear_x() {
  _impl_.x_ = 0;
}
inline float FVector::_internal_x() const {
  return _impl_.x_;
}
inline float FVector::x() const {
  // @@protoc_insertion_point(field_get:unrealpb.FVector.x)
  return _internal_x();
}
inline void FVector::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void FVector::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:unrealpb.FVector.x)
}

// float y = 2;
inline void FVector::clear_y() {
  _impl_.y_ = 0;
}
inline float FVector::_internal_y() const {
  return _impl_.y_;
}
inline float FVector::y() const {
  // @@protoc_insertion_point(field_get:unrealpb.FVector.y)
  return _internal_y();
}
inline void FVector::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void FVector::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:unrealpb.FVector.y)
}

// float z = 3;
inline void FVector::clear_z() {
  _impl_.z_ = 0;
}
inline float FVector::_internal_z() const {
  return _impl_.z_;
}
inline float FVector::z() const {
  // @@protoc_insertion_point(field_get:unrealpb.FVector.z)
  return _internal_z();
}
inline void FVector::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void FVector::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:unrealpb.FVector.z)
}

// -------------------------------------------------------------------

// UnrealObjectRef

// uint32 NetGUID = 1;
inline void UnrealObjectRef::clear_netguid() {
  _impl_.netguid_ = 0u;
}
inline uint32_t UnrealObjectRef::_internal_netguid() const {
  return _impl_.netguid_;
}
inline uint32_t UnrealObjectRef::netguid() const {
  // @@protoc_insertion_point(field_get:unrealpb.UnrealObjectRef.NetGUID)
  return _internal_netguid();
}
inline void UnrealObjectRef::_internal_set_netguid(uint32_t value) {
  
  _impl_.netguid_ = value;
}
inline void UnrealObjectRef::set_netguid(uint32_t value) {
  _internal_set_netguid(value);
  // @@protoc_insertion_point(field_set:unrealpb.UnrealObjectRef.NetGUID)
}

// -------------------------------------------------------------------

// SceneComponentState

// bool removed = 1;
inline void SceneComponentState::clear_removed() {
  _impl_.removed_ = false;
}
inline bool SceneComponentState::_internal_removed() const {
  return _impl_.removed_;
}
inline bool SceneComponentState::removed() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.removed)
  return _internal_removed();
}
inline void SceneComponentState::_internal_set_removed(bool value) {
  
  _impl_.removed_ = value;
}
inline void SceneComponentState::set_removed(bool value) {
  _internal_set_removed(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.removed)
}

// bool bAbsoluteLocation = 2;
inline void SceneComponentState::clear_babsolutelocation() {
  _impl_.babsolutelocation_ = false;
}
inline bool SceneComponentState::_internal_babsolutelocation() const {
  return _impl_.babsolutelocation_;
}
inline bool SceneComponentState::babsolutelocation() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bAbsoluteLocation)
  return _internal_babsolutelocation();
}
inline void SceneComponentState::_internal_set_babsolutelocation(bool value) {
  
  _impl_.babsolutelocation_ = value;
}
inline void SceneComponentState::set_babsolutelocation(bool value) {
  _internal_set_babsolutelocation(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bAbsoluteLocation)
}

// bool bAbsoluteRotation = 3;
inline void SceneComponentState::clear_babsoluterotation() {
  _impl_.babsoluterotation_ = false;
}
inline bool SceneComponentState::_internal_babsoluterotation() const {
  return _impl_.babsoluterotation_;
}
inline bool SceneComponentState::babsoluterotation() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bAbsoluteRotation)
  return _internal_babsoluterotation();
}
inline void SceneComponentState::_internal_set_babsoluterotation(bool value) {
  
  _impl_.babsoluterotation_ = value;
}
inline void SceneComponentState::set_babsoluterotation(bool value) {
  _internal_set_babsoluterotation(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bAbsoluteRotation)
}

// bool bAbsoluteScale = 4;
inline void SceneComponentState::clear_babsolutescale() {
  _impl_.babsolutescale_ = false;
}
inline bool SceneComponentState::_internal_babsolutescale() const {
  return _impl_.babsolutescale_;
}
inline bool SceneComponentState::babsolutescale() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bAbsoluteScale)
  return _internal_babsolutescale();
}
inline void SceneComponentState::_internal_set_babsolutescale(bool value) {
  
  _impl_.babsolutescale_ = value;
}
inline void SceneComponentState::set_babsolutescale(bool value) {
  _internal_set_babsolutescale(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bAbsoluteScale)
}

// bool bVisible = 5;
inline void SceneComponentState::clear_bvisible() {
  _impl_.bvisible_ = false;
}
inline bool SceneComponentState::_internal_bvisible() const {
  return _impl_.bvisible_;
}
inline bool SceneComponentState::bvisible() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bVisible)
  return _internal_bvisible();
}
inline void SceneComponentState::_internal_set_bvisible(bool value) {
  
  _impl_.bvisible_ = value;
}
inline void SceneComponentState::set_bvisible(bool value) {
  _internal_set_bvisible(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bVisible)
}

// bool bShouldBeAttached = 6;
inline void SceneComponentState::clear_bshouldbeattached() {
  _impl_.bshouldbeattached_ = false;
}
inline bool SceneComponentState::_internal_bshouldbeattached() const {
  return _impl_.bshouldbeattached_;
}
inline bool SceneComponentState::bshouldbeattached() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bShouldBeAttached)
  return _internal_bshouldbeattached();
}
inline void SceneComponentState::_internal_set_bshouldbeattached(bool value) {
  
  _impl_.bshouldbeattached_ = value;
}
inline void SceneComponentState::set_bshouldbeattached(bool value) {
  _internal_set_bshouldbeattached(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bShouldBeAttached)
}

// bool bShouldSnapLocationWhenAttached = 7;
inline void SceneComponentState::clear_bshouldsnaplocationwhenattached() {
  _impl_.bshouldsnaplocationwhenattached_ = false;
}
inline bool SceneComponentState::_internal_bshouldsnaplocationwhenattached() const {
  return _impl_.bshouldsnaplocationwhenattached_;
}
inline bool SceneComponentState::bshouldsnaplocationwhenattached() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bShouldSnapLocationWhenAttached)
  return _internal_bshouldsnaplocationwhenattached();
}
inline void SceneComponentState::_internal_set_bshouldsnaplocationwhenattached(bool value) {
  
  _impl_.bshouldsnaplocationwhenattached_ = value;
}
inline void SceneComponentState::set_bshouldsnaplocationwhenattached(bool value) {
  _internal_set_bshouldsnaplocationwhenattached(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bShouldSnapLocationWhenAttached)
}

// bool bShouldSnapRotationWhenAttached = 8;
inline void SceneComponentState::clear_bshouldsnaprotationwhenattached() {
  _impl_.bshouldsnaprotationwhenattached_ = false;
}
inline bool SceneComponentState::_internal_bshouldsnaprotationwhenattached() const {
  return _impl_.bshouldsnaprotationwhenattached_;
}
inline bool SceneComponentState::bshouldsnaprotationwhenattached() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.bShouldSnapRotationWhenAttached)
  return _internal_bshouldsnaprotationwhenattached();
}
inline void SceneComponentState::_internal_set_bshouldsnaprotationwhenattached(bool value) {
  
  _impl_.bshouldsnaprotationwhenattached_ = value;
}
inline void SceneComponentState::set_bshouldsnaprotationwhenattached(bool value) {
  _internal_set_bshouldsnaprotationwhenattached(value);
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.bShouldSnapRotationWhenAttached)
}

// .unrealpb.UnrealObjectRef attachParent = 9;
inline bool SceneComponentState::_internal_has_attachparent() const {
  return this != internal_default_instance() && _impl_.attachparent_ != nullptr;
}
inline bool SceneComponentState::has_attachparent() const {
  return _internal_has_attachparent();
}
inline void SceneComponentState::clear_attachparent() {
  if (GetArenaForAllocation() == nullptr && _impl_.attachparent_ != nullptr) {
    delete _impl_.attachparent_;
  }
  _impl_.attachparent_ = nullptr;
}
inline const ::unrealpb::UnrealObjectRef& SceneComponentState::_internal_attachparent() const {
  const ::unrealpb::UnrealObjectRef* p = _impl_.attachparent_;
  return p != nullptr ? *p : reinterpret_cast<const ::unrealpb::UnrealObjectRef&>(
      ::unrealpb::_UnrealObjectRef_default_instance_);
}
inline const ::unrealpb::UnrealObjectRef& SceneComponentState::attachparent() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.attachParent)
  return _internal_attachparent();
}
inline void SceneComponentState::unsafe_arena_set_allocated_attachparent(
    ::unrealpb::UnrealObjectRef* attachparent) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.attachparent_);
  }
  _impl_.attachparent_ = attachparent;
  if (attachparent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:unrealpb.SceneComponentState.attachParent)
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::release_attachparent() {
  
  ::unrealpb::UnrealObjectRef* temp = _impl_.attachparent_;
  _impl_.attachparent_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::unsafe_arena_release_attachparent() {
  // @@protoc_insertion_point(field_release:unrealpb.SceneComponentState.attachParent)
  
  ::unrealpb::UnrealObjectRef* temp = _impl_.attachparent_;
  _impl_.attachparent_ = nullptr;
  return temp;
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::_internal_mutable_attachparent() {
  
  if (_impl_.attachparent_ == nullptr) {
    auto* p = CreateMaybeMessage<::unrealpb::UnrealObjectRef>(GetArenaForAllocation());
    _impl_.attachparent_ = p;
  }
  return _impl_.attachparent_;
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::mutable_attachparent() {
  ::unrealpb::UnrealObjectRef* _msg = _internal_mutable_attachparent();
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.attachParent)
  return _msg;
}
inline void SceneComponentState::set_allocated_attachparent(::unrealpb::UnrealObjectRef* attachparent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.attachparent_;
  }
  if (attachparent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(attachparent);
    if (message_arena != submessage_arena) {
      attachparent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, attachparent, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.attachparent_ = attachparent;
  // @@protoc_insertion_point(field_set_allocated:unrealpb.SceneComponentState.attachParent)
}

// repeated .unrealpb.UnrealObjectRef attachChildren = 10;
inline int SceneComponentState::_internal_attachchildren_size() const {
  return _impl_.attachchildren_.size();
}
inline int SceneComponentState::attachchildren_size() const {
  return _internal_attachchildren_size();
}
inline void SceneComponentState::clear_attachchildren() {
  _impl_.attachchildren_.Clear();
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::mutable_attachchildren(int index) {
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.attachChildren)
  return _impl_.attachchildren_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::unrealpb::UnrealObjectRef >*
SceneComponentState::mutable_attachchildren() {
  // @@protoc_insertion_point(field_mutable_list:unrealpb.SceneComponentState.attachChildren)
  return &_impl_.attachchildren_;
}
inline const ::unrealpb::UnrealObjectRef& SceneComponentState::_internal_attachchildren(int index) const {
  return _impl_.attachchildren_.Get(index);
}
inline const ::unrealpb::UnrealObjectRef& SceneComponentState::attachchildren(int index) const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.attachChildren)
  return _internal_attachchildren(index);
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::_internal_add_attachchildren() {
  return _impl_.attachchildren_.Add();
}
inline ::unrealpb::UnrealObjectRef* SceneComponentState::add_attachchildren() {
  ::unrealpb::UnrealObjectRef* _add = _internal_add_attachchildren();
  // @@protoc_insertion_point(field_add:unrealpb.SceneComponentState.attachChildren)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::unrealpb::UnrealObjectRef >&
SceneComponentState::attachchildren() const {
  // @@protoc_insertion_point(field_list:unrealpb.SceneComponentState.attachChildren)
  return _impl_.attachchildren_;
}

// string attachSocketName = 11;
inline void SceneComponentState::clear_attachsocketname() {
  _impl_.attachsocketname_.ClearToEmpty();
}
inline const std::string& SceneComponentState::attachsocketname() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.attachSocketName)
  return _internal_attachsocketname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SceneComponentState::set_attachsocketname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.attachsocketname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:unrealpb.SceneComponentState.attachSocketName)
}
inline std::string* SceneComponentState::mutable_attachsocketname() {
  std::string* _s = _internal_mutable_attachsocketname();
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.attachSocketName)
  return _s;
}
inline const std::string& SceneComponentState::_internal_attachsocketname() const {
  return _impl_.attachsocketname_.Get();
}
inline void SceneComponentState::_internal_set_attachsocketname(const std::string& value) {
  
  _impl_.attachsocketname_.Set(value, GetArenaForAllocation());
}
inline std::string* SceneComponentState::_internal_mutable_attachsocketname() {
  
  return _impl_.attachsocketname_.Mutable(GetArenaForAllocation());
}
inline std::string* SceneComponentState::release_attachsocketname() {
  // @@protoc_insertion_point(field_release:unrealpb.SceneComponentState.attachSocketName)
  return _impl_.attachsocketname_.Release();
}
inline void SceneComponentState::set_allocated_attachsocketname(std::string* attachsocketname) {
  if (attachsocketname != nullptr) {
    
  } else {
    
  }
  _impl_.attachsocketname_.SetAllocated(attachsocketname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.attachsocketname_.IsDefault()) {
    _impl_.attachsocketname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:unrealpb.SceneComponentState.attachSocketName)
}

// .unrealpb.FVector relativeLocation = 12;
inline bool SceneComponentState::_internal_has_relativelocation() const {
  return this != internal_default_instance() && _impl_.relativelocation_ != nullptr;
}
inline bool SceneComponentState::has_relativelocation() const {
  return _internal_has_relativelocation();
}
inline void SceneComponentState::clear_relativelocation() {
  if (GetArenaForAllocation() == nullptr && _impl_.relativelocation_ != nullptr) {
    delete _impl_.relativelocation_;
  }
  _impl_.relativelocation_ = nullptr;
}
inline const ::unrealpb::FVector& SceneComponentState::_internal_relativelocation() const {
  const ::unrealpb::FVector* p = _impl_.relativelocation_;
  return p != nullptr ? *p : reinterpret_cast<const ::unrealpb::FVector&>(
      ::unrealpb::_FVector_default_instance_);
}
inline const ::unrealpb::FVector& SceneComponentState::relativelocation() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.relativeLocation)
  return _internal_relativelocation();
}
inline void SceneComponentState::unsafe_arena_set_allocated_relativelocation(
    ::unrealpb::FVector* relativelocation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.relativelocation_);
  }
  _impl_.relativelocation_ = relativelocation;
  if (relativelocation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:unrealpb.SceneComponentState.relativeLocation)
}
inline ::unrealpb::FVector* SceneComponentState::release_relativelocation() {
  
  ::unrealpb::FVector* temp = _impl_.relativelocation_;
  _impl_.relativelocation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::unsafe_arena_release_relativelocation() {
  // @@protoc_insertion_point(field_release:unrealpb.SceneComponentState.relativeLocation)
  
  ::unrealpb::FVector* temp = _impl_.relativelocation_;
  _impl_.relativelocation_ = nullptr;
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::_internal_mutable_relativelocation() {
  
  if (_impl_.relativelocation_ == nullptr) {
    auto* p = CreateMaybeMessage<::unrealpb::FVector>(GetArenaForAllocation());
    _impl_.relativelocation_ = p;
  }
  return _impl_.relativelocation_;
}
inline ::unrealpb::FVector* SceneComponentState::mutable_relativelocation() {
  ::unrealpb::FVector* _msg = _internal_mutable_relativelocation();
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.relativeLocation)
  return _msg;
}
inline void SceneComponentState::set_allocated_relativelocation(::unrealpb::FVector* relativelocation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.relativelocation_;
  }
  if (relativelocation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(relativelocation);
    if (message_arena != submessage_arena) {
      relativelocation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, relativelocation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.relativelocation_ = relativelocation;
  // @@protoc_insertion_point(field_set_allocated:unrealpb.SceneComponentState.relativeLocation)
}

// .unrealpb.FVector relativeRotation = 13;
inline bool SceneComponentState::_internal_has_relativerotation() const {
  return this != internal_default_instance() && _impl_.relativerotation_ != nullptr;
}
inline bool SceneComponentState::has_relativerotation() const {
  return _internal_has_relativerotation();
}
inline void SceneComponentState::clear_relativerotation() {
  if (GetArenaForAllocation() == nullptr && _impl_.relativerotation_ != nullptr) {
    delete _impl_.relativerotation_;
  }
  _impl_.relativerotation_ = nullptr;
}
inline const ::unrealpb::FVector& SceneComponentState::_internal_relativerotation() const {
  const ::unrealpb::FVector* p = _impl_.relativerotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::unrealpb::FVector&>(
      ::unrealpb::_FVector_default_instance_);
}
inline const ::unrealpb::FVector& SceneComponentState::relativerotation() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.relativeRotation)
  return _internal_relativerotation();
}
inline void SceneComponentState::unsafe_arena_set_allocated_relativerotation(
    ::unrealpb::FVector* relativerotation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.relativerotation_);
  }
  _impl_.relativerotation_ = relativerotation;
  if (relativerotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:unrealpb.SceneComponentState.relativeRotation)
}
inline ::unrealpb::FVector* SceneComponentState::release_relativerotation() {
  
  ::unrealpb::FVector* temp = _impl_.relativerotation_;
  _impl_.relativerotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::unsafe_arena_release_relativerotation() {
  // @@protoc_insertion_point(field_release:unrealpb.SceneComponentState.relativeRotation)
  
  ::unrealpb::FVector* temp = _impl_.relativerotation_;
  _impl_.relativerotation_ = nullptr;
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::_internal_mutable_relativerotation() {
  
  if (_impl_.relativerotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::unrealpb::FVector>(GetArenaForAllocation());
    _impl_.relativerotation_ = p;
  }
  return _impl_.relativerotation_;
}
inline ::unrealpb::FVector* SceneComponentState::mutable_relativerotation() {
  ::unrealpb::FVector* _msg = _internal_mutable_relativerotation();
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.relativeRotation)
  return _msg;
}
inline void SceneComponentState::set_allocated_relativerotation(::unrealpb::FVector* relativerotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.relativerotation_;
  }
  if (relativerotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(relativerotation);
    if (message_arena != submessage_arena) {
      relativerotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, relativerotation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.relativerotation_ = relativerotation;
  // @@protoc_insertion_point(field_set_allocated:unrealpb.SceneComponentState.relativeRotation)
}

// .unrealpb.FVector relativeScale = 14;
inline bool SceneComponentState::_internal_has_relativescale() const {
  return this != internal_default_instance() && _impl_.relativescale_ != nullptr;
}
inline bool SceneComponentState::has_relativescale() const {
  return _internal_has_relativescale();
}
inline void SceneComponentState::clear_relativescale() {
  if (GetArenaForAllocation() == nullptr && _impl_.relativescale_ != nullptr) {
    delete _impl_.relativescale_;
  }
  _impl_.relativescale_ = nullptr;
}
inline const ::unrealpb::FVector& SceneComponentState::_internal_relativescale() const {
  const ::unrealpb::FVector* p = _impl_.relativescale_;
  return p != nullptr ? *p : reinterpret_cast<const ::unrealpb::FVector&>(
      ::unrealpb::_FVector_default_instance_);
}
inline const ::unrealpb::FVector& SceneComponentState::relativescale() const {
  // @@protoc_insertion_point(field_get:unrealpb.SceneComponentState.relativeScale)
  return _internal_relativescale();
}
inline void SceneComponentState::unsafe_arena_set_allocated_relativescale(
    ::unrealpb::FVector* relativescale) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.relativescale_);
  }
  _impl_.relativescale_ = relativescale;
  if (relativescale) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:unrealpb.SceneComponentState.relativeScale)
}
inline ::unrealpb::FVector* SceneComponentState::release_relativescale() {
  
  ::unrealpb::FVector* temp = _impl_.relativescale_;
  _impl_.relativescale_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::unsafe_arena_release_relativescale() {
  // @@protoc_insertion_point(field_release:unrealpb.SceneComponentState.relativeScale)
  
  ::unrealpb::FVector* temp = _impl_.relativescale_;
  _impl_.relativescale_ = nullptr;
  return temp;
}
inline ::unrealpb::FVector* SceneComponentState::_internal_mutable_relativescale() {
  
  if (_impl_.relativescale_ == nullptr) {
    auto* p = CreateMaybeMessage<::unrealpb::FVector>(GetArenaForAllocation());
    _impl_.relativescale_ = p;
  }
  return _impl_.relativescale_;
}
inline ::unrealpb::FVector* SceneComponentState::mutable_relativescale() {
  ::unrealpb::FVector* _msg = _internal_mutable_relativescale();
  // @@protoc_insertion_point(field_mutable:unrealpb.SceneComponentState.relativeScale)
  return _msg;
}
inline void SceneComponentState::set_allocated_relativescale(::unrealpb::FVector* relativescale) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.relativescale_;
  }
  if (relativescale) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(relativescale);
    if (message_arena != submessage_arena) {
      relativescale = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, relativescale, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.relativescale_ = relativescale;
  // @@protoc_insertion_point(field_set_allocated:unrealpb.SceneComponentState.relativeScale)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace unrealpb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_unreal_5fcommon_2eproto
